// src/types/aliases.ts
import type { components, paths } from "./api"; // <-- generated by openapi-typescript

// Aliases for commonly used schemas
export type AcademicProgram = components["schemas"]["AcademicProgram"]
export type AcademicProgramBase = components["schemas"]["AcademicProgramBase"]
export type AcademicProgramCreate = components["schemas"]["AcademicProgramCreate"]
export type AcademicProgramUpdate = components["schemas"]["AcademicProgramUpdate"]
export type Assignment = components["schemas"]["Assignment"]
export type AssignmentCreate = components["schemas"]["AssignmentCreate"]
export type AssignmentUpdate = components["schemas"]["AssignmentUpdate"]
export type Course = components["schemas"]["Course"]
export type CourseAssignment = components["schemas"]["CourseAssignment"]
export type CourseAssignmentCreate = components["schemas"]["CourseAssignmentCreate"]
export type CourseAssignmentUpdate = components["schemas"]["CourseAssignmentUpdate"]
export type CourseCreate = components["schemas"]["CourseCreate"]
export type CourseInstance = components["schemas"]["CourseInstance"]
export type CourseInstanceBase = components["schemas"]["CourseInstanceBase"]
export type CourseInstanceCreate = components["schemas"]["CourseInstanceCreate"]
export type CourseInstanceUpdate = components["schemas"]["CourseInstanceUpdate"]
export type CourseUpdate = components["schemas"]["CourseUpdate"]
export type Department = components["schemas"]["Department"]
export type DepartmentCreate = components["schemas"]["DepartmentCreate"]
export type DepartmentUpdate = components["schemas"]["DepartmentUpdate"]
export type EnrollStudentRequest = components["schemas"]["EnrollStudentRequest"]
export type Faculty = components["schemas"]["Faculty"]
export type FacultyCreate = components["schemas"]["FacultyCreate"]
export type FacultyUpdate = components["schemas"]["FacultyUpdate"]
export type HTTPValidationError = components["schemas"]["HTTPValidationError"]
export type Job = components["schemas"]["Job"]
export type JobCreate = components["schemas"]["JobCreate"]
export type JobUpdate = components["schemas"]["JobUpdate"]
export type ProgramCourseRequirement = components["schemas"]["ProgramCourseRequirement"]
export type ProgramCourseRequirementCreate = components["schemas"]["ProgramCourseRequirementCreate"]
export type ProgramCourseRequirementUpdate = components["schemas"]["ProgramCourseRequirementUpdate"]
export type Roles = components["schemas"]["Roles"]
export type RolesCreate = components["schemas"]["RolesCreate"]
export type RolesUpdate = components["schemas"]["RolesUpdate"]
export type Student = components["schemas"]["Student"]
export type StudentCreate = components["schemas"]["StudentCreate"]
export type StudentUpdate = components["schemas"]["StudentUpdate"]
export type Users = components["schemas"]["Users"]
export type UsersCreate = components["schemas"]["UsersCreate"]
export type UsersUpdate = components["schemas"]["UsersUpdate"]
export type ValidationError = components["schemas"]["ValidationError"]

export type Body_login_for_access_token_auth_token_post =   
    components["schemas"]["Body_login_for_access_token_auth_token_post"]

// // Aliases for endpoint-specific responses (optional)
// export type ListStudentsResponse =
//   paths["/students/"]["get"]["responses"]["200"]["content"]["application/json"];