/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic_programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Academic Programs */
        get: operations["list_academic_programs_academic_programs__get"];
        put?: never;
        /** Create Academic Program */
        post: operations["create_academic_program_academic_programs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic_programs/{academic_program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Academic Program */
        get: operations["get_academic_program_academic_programs__academic_program_id__get"];
        /** Update Academic Program */
        put: operations["update_academic_program_academic_programs__academic_program_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_assignments__get"];
        put?: never;
        /** Create Assignment */
        post: operations["create_assignment_assignments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assignment */
        get: operations["get_assignment_assignments__assignment_id__get"];
        /** Update Assignment */
        put: operations["update_assignment_assignments__assignment_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Assignments */
        get: operations["list_course_assignments_course_assignments__get"];
        put?: never;
        /** Create Course Assignment */
        post: operations["create_course_assignment_course_assignments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_assignments/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Assignments By Student */
        get: operations["list_course_assignments_by_student_course_assignments__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_assignments/{course_assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Assignment */
        get: operations["get_course_assignment_course_assignments__course_assignment_id__get"];
        /** Update Course Assignment */
        put: operations["update_course_assignment_course_assignments__course_assignment_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_instances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Instances */
        get: operations["list_course_instances_course_instances__get"];
        put?: never;
        /** Create Course Instance */
        post: operations["create_course_instance_course_instances__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_instances/{course_instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Instance */
        get: operations["get_course_instance_course_instances__course_instance_id__get"];
        /** Update Course Instance */
        put: operations["update_course_instance_course_instances__course_instance_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course_instances/{course_instance_id}/enroll-student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Student */
        post: operations["enroll_student_course_instances__course_instance_id__enroll_student_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_courses__get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_courses__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__course_id__get"];
        /** Update Course */
        put: operations["update_course_courses__course_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deparments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Departments */
        get: operations["list_departments_deparments__get"];
        put?: never;
        /** Create Department */
        post: operations["create_department_deparments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deparments/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Department */
        get: operations["get_department_deparments__department_id__get"];
        /** Update Department */
        put: operations["update_department_deparments__department_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculty/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Faculty */
        get: operations["list_faculty_faculty__get"];
        put?: never;
        /** Create Faculty */
        post: operations["create_faculty_faculty__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculty/{faculty_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Faculty */
        get: operations["get_faculty_faculty__faculty_id__get"];
        /** Update Faculty */
        put: operations["update_faculty_faculty__faculty_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculty/{faculty_id}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Faculty Classes */
        get: operations["get_faculty_classes_faculty__faculty_id__classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs__get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        /** Update Job */
        put: operations["update_job_jobs__job_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program_course_requirements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Program Course Requirements */
        get: operations["list_program_course_requirements_program_course_requirements__get"];
        put?: never;
        /** Create Program Course Requirement */
        post: operations["create_program_course_requirement_program_course_requirements__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program_course_requirements/{program_course_requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Course Requirement */
        get: operations["get_program_course_requirement_program_course_requirements__program_course_requirement_id__get"];
        /** Update Program Course Requirement */
        put: operations["update_program_course_requirement_program_course_requirements__program_course_requirement_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_students__get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_students__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_students__student_id__get"];
        /** Update Student */
        put: operations["update_student_students__student_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_Users_users__get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Job */
        put: operations["update_job_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_roles__get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_roles__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role */
        get: operations["get_role_roles__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Job */
        put: operations["update_job_roles__role_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcademicProgram */
        AcademicProgram: {
            /** Name */
            name: string;
            /** Department */
            department: number;
            /** Degree Type */
            degree_type: string;
            /** Program Id */
            program_id: number;
        };
        /** AcademicProgramBase */
        AcademicProgramBase: {
            /** Name */
            name: string;
            /** Department */
            department: number;
            /** Degree Type */
            degree_type: string;
        };
        /** AcademicProgramCreate */
        AcademicProgramCreate: {
            /** Name */
            name: string;
            /** Department */
            department: number;
            /** Degree Type */
            degree_type: string;
        };
        /** AcademicProgramUpdate */
        AcademicProgramUpdate: {
            /** Name */
            name?: string | null;
            /** Department */
            department?: number | null;
            /** Degree Type */
            degree_type?: string | null;
        };
        /** Assignment */
        Assignment: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Is Active */
            is_active: boolean;
            /** Max Points */
            max_points: number;
            /** End Date */
            end_date: string | null;
            /** Assignment Id */
            assignment_id: number;
        };
        /** AssignmentCreate */
        AssignmentCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Is Active */
            is_active: boolean;
            /** Max Points */
            max_points: number;
            /** End Date */
            end_date: string | null;
        };
        /** AssignmentUpdate */
        AssignmentUpdate: {
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Max Points */
            max_points?: number | null;
            /** End Date */
            end_date?: string | null;
        };
        /** Body_login_for_access_token_auth_token_post */
        Body_login_for_access_token_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Course */
        Course: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Is Active */
            is_active: boolean | null;
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Credits */
            credits: number;
            /** Course Id */
            course_id: number;
        };
        /** CourseAssignment */
        CourseAssignment: {
            /** Instance Id */
            instance_id: number;
            /** Assignment Id */
            assignment_id: number;
            /** Student Id */
            student_id: number;
            /** Points Earned */
            points_earned: number | null;
            /** Letter Grade */
            letter_grade: string | null;
            /** Course Assignment Id */
            course_assignment_id: number;
            assignment: components["schemas"]["Assignment"] | null;
        };
        /** CourseAssignmentCreate */
        CourseAssignmentCreate: {
            /** Instance Id */
            instance_id: number;
            /** Assignment Id */
            assignment_id: number;
            /** Student Id */
            student_id: number;
            /** Points Earned */
            points_earned: number | null;
            /** Letter Grade */
            letter_grade: string | null;
        };
        /** CourseAssignmentUpdate */
        CourseAssignmentUpdate: {
            /** Instance Id */
            instance_id?: number | null;
            /** Assignment Id */
            assignment_id?: number | null;
            /** Student Id */
            student_id?: number | null;
            /** Points Earned */
            points_earned?: number | null;
            /** Letter Grade */
            letter_grade?: string | null;
        };
        /** CourseCreate */
        CourseCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Is Active */
            is_active: boolean | null;
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Credits */
            credits: number;
        };
        /** CourseInstance */
        CourseInstance: {
            /** Course Id */
            course_id: number;
            /** Faculty Id */
            faculty_id: number;
            /** Term */
            term: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Location */
            location: string;
            /** End Date */
            end_date: string | null;
            /** Instance Id */
            instance_id: number;
            /**
             * Students
             * @default []
             */
            students: components["schemas"]["Student"][];
        };
        /** CourseInstanceBase */
        CourseInstanceBase: {
            /** Course Id */
            course_id: number;
            /** Faculty Id */
            faculty_id: number;
            /** Term */
            term: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Location */
            location: string;
            /** End Date */
            end_date: string | null;
        };
        /** CourseInstanceCreate */
        CourseInstanceCreate: {
            /** Course Id */
            course_id: number;
            /** Faculty Id */
            faculty_id: number;
            /** Term */
            term: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Location */
            location: string;
            /** End Date */
            end_date: string | null;
        };
        /** CourseInstanceUpdate */
        CourseInstanceUpdate: {
            /** Course Id */
            course_id?: number | null;
            /** Faculty Id */
            faculty_id?: number | null;
            /** Term */
            term?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Location */
            location?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** CourseUpdate */
        CourseUpdate: {
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** Department */
        Department: {
            /** Name */
            name: string;
            /** Department Id */
            department_id: number;
        };
        /** DepartmentCreate */
        DepartmentCreate: {
            /** Name */
            name: string;
        };
        /** DepartmentUpdate */
        DepartmentUpdate: {
            /** Name */
            name?: string | null;
        };
        /** EnrollStudentRequest */
        EnrollStudentRequest: {
            /** Student Id */
            student_id: number;
        };
        /** Faculty */
        Faculty: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Hire Date
             * Format: date-time
             */
            hire_date: string;
            /** Department Id */
            department_id: number;
            /** Job Id */
            job_id: number;
            /** Term Date */
            term_date: string | null;
            /** Email Address */
            email_address: string | null;
            /** Faculty Id */
            faculty_id: number;
        };
        /** FacultyCreate */
        FacultyCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Hire Date
             * Format: date-time
             */
            hire_date: string;
            /** Department Id */
            department_id: number;
            /** Job Id */
            job_id: number;
            /** Term Date */
            term_date: string | null;
            /** Email Address */
            email_address: string | null;
        };
        /** FacultyUpdate */
        FacultyUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Hire Date */
            hire_date?: string | null;
            /** Department Id */
            department_id?: number | null;
            /** Job Id */
            job_id?: number | null;
            /** Term Date */
            term_date?: string | null;
            /** Email Address */
            email_address?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Is Active */
            is_active: boolean;
            /** Is Management */
            is_management: boolean;
            /** End Date */
            end_date: string | null;
            /** Job Id */
            job_id: number;
        };
        /** JobCreate */
        JobCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Is Active */
            is_active: boolean;
            /** Is Management */
            is_management: boolean;
            /** End Date */
            end_date: string | null;
        };
        /** JobUpdate */
        JobUpdate: {
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Management */
            is_management?: boolean | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ProgramCourseRequirement */
        ProgramCourseRequirement: {
            /** Program Id */
            program_id: number;
            /** Course Id */
            course_id: number;
            /** Requirement Type */
            requirement_type: string;
            /** Version */
            version: string;
            /** Requirement Id */
            requirement_id: number;
        };
        /** ProgramCourseRequirementCreate */
        ProgramCourseRequirementCreate: {
            /** Program Id */
            program_id: number;
            /** Course Id */
            course_id: number;
            /** Requirement Type */
            requirement_type: string;
            /** Version */
            version: string;
        };
        /** ProgramCourseRequirementUpdate */
        ProgramCourseRequirementUpdate: {
            /** Program Id */
            program_id?: number | null;
            /** Course Id */
            course_id?: number | null;
            /** Requirement Type */
            requirement_type?: string | null;
            /** Version */
            version?: string | null;
        };
        /** Roles */
        Roles: {
            /** Name */
            name: string;
            /** Id */
            id: number;
        };
        /** RolesCreate */
        RolesCreate: {
            /** Name */
            name: string;
        };
        /** RolesUpdate */
        RolesUpdate: {
            /** Name */
            name?: string | null;
        };
        /** Student */
        Student: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * Expected Graduation Date
             * Format: date-time
             */
            expected_graduation_date: string;
            /** Program Id */
            program_id: number;
            /** End Date */
            end_date: string | null;
            /** Email Address */
            email_address: string | null;
            /**
             * Course Instances
             * @default []
             */
            course_instances: components["schemas"]["CourseInstanceBase"][];
            program: components["schemas"]["AcademicProgramBase"] | null;
            /** Student Id */
            student_id: number;
        };
        /** StudentCreate */
        StudentCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * Expected Graduation Date
             * Format: date-time
             */
            expected_graduation_date: string;
            /** Program Id */
            program_id: number;
            /** End Date */
            end_date: string | null;
            /** Email Address */
            email_address: string | null;
            /**
             * Course Instances
             * @default []
             */
            course_instances: components["schemas"]["CourseInstanceBase"][];
            program: components["schemas"]["AcademicProgramBase"] | null;
        };
        /** StudentUpdate */
        StudentUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Expected Graduation Date */
            expected_graduation_date?: string | null;
            /** Program Id */
            program_id?: number | null;
            /** End Date */
            end_date?: string | null;
            /** Email Address */
            email_address?: string | null;
        };
        /** Users */
        Users: {
            /** Username */
            username: string;
            /** Is Active */
            is_active: boolean | null;
            /** Id */
            id: number;
        };
        /** UsersCreate */
        UsersCreate: {
            /** Username */
            username: string;
            /** Is Active */
            is_active: boolean | null;
            /**
             * Password
             * @example strongpassword123
             */
            password: string;
            /**
             * Roles
             * @default []
             */
            roles: number[];
        };
        /** UsersUpdate */
        UsersUpdate: {
            /** Username */
            username?: string | null;
            /**
             * Password
             * @example strongpassword123
             */
            password: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Roles
             * @default []
             */
            roles: number[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_academic_programs_academic_programs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicProgram"][];
                };
            };
        };
    };
    create_academic_program_academic_programs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicProgramCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicProgram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_academic_program_academic_programs__academic_program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                academic_program_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicProgram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_academic_program_academic_programs__academic_program_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                academic_program_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicProgramUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicProgram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_assignments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
        };
    };
    create_assignment_assignments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignment_assignments__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assignment_assignments__assignment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_assignments_course_assignments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAssignment"][];
                };
            };
        };
    };
    create_course_assignment_course_assignments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseAssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_assignments_by_student_course_assignments__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAssignment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_assignment_course_assignments__course_assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_assignment_course_assignments__course_assignment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_assignment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseAssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_instances_course_instances__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseInstance"][];
                };
            };
        };
    };
    create_course_instance_course_instances__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseInstanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_instance_course_instances__course_instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_instance_course_instances__course_instance_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_instance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseInstanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_student_course_instances__course_instance_id__enroll_student_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_instance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollStudentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_courses__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    create_course_courses__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_courses__course_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_deparments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
    create_department_deparments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_department_deparments__department_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_department_deparments__department_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_faculty_faculty__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faculty"][];
                };
            };
        };
    };
    create_faculty_faculty__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacultyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faculty"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_faculty_faculty__faculty_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faculty_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faculty"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_faculty_faculty__faculty_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faculty_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacultyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faculty"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_faculty_classes_faculty__faculty_id__classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faculty_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    create_job_jobs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_program_course_requirements_program_course_requirements__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramCourseRequirement"][];
                };
            };
        };
    };
    create_program_course_requirement_program_course_requirements__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramCourseRequirementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramCourseRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_course_requirement_program_course_requirements__program_course_requirement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_course_requirement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramCourseRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_program_course_requirement_program_course_requirements__program_course_requirement_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_course_requirement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramCourseRequirementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramCourseRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_students__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    create_student_students__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_students__student_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_Users_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"][];
                };
            };
        };
    };
    create_user_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsersCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsersUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_roles__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roles"][];
                };
            };
        };
    };
    create_role_roles__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_roles__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_roles__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
