CREATE SCHEMA IF NOT EXISTS SCHOOL;

-- JOB
CREATE TABLE IF NOT EXISTS SCHOOL.JOB (
    JOB_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN,
    IS_MANAGEMENT BOOLEAN
);

-- DEPARTMENT
CREATE TABLE IF NOT EXISTS SCHOOL.DEPARTMENT (
    DEPARTMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

-- FACULTY
CREATE TABLE IF NOT EXISTS SCHOOL.FACULTY (
    FACULTY_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    HIRE_DATE DATE,
    TERM_DATE DATE NOT NULL,
    DEPARTMENT_ID INT REFERENCES SCHOOL.DEPARTMENT(DEPARTMENT_ID),
    JOB_ID INT REFERENCES SCHOOL.JOB(JOB_ID)
);

-- ACADEMIC_PROGRAM
CREATE TABLE IF NOT EXISTS SCHOOL.ACADEMIC_PROGRAM (
    PROGRAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    DEPARTMENT INT REFERENCES SCHOOL.DEPARTMENT(DEPARTMENT_ID),
    DEGREE_TYPE VARCHAR(20)
);

-- STUDENT
CREATE TABLE IF NOT EXISTS SCHOOL.STUDENT (
    STUDENT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    EXPECTED_GRADUATION_DATE DATE,
    PROGRAM_ID INT REFERENCES SCHOOL.ACADEMIC_PROGRAM(PROGRAM_ID)
);

-- COURSE
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE (
    COURSE_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN
);

-- PROGRAM_COURSE_REQUIREMENT
CREATE TABLE IF NOT EXISTS SCHOOL.PROGRAM_COURSE_REQUIREMENT (
    REQUIREMENT_ID SERIAL PRIMARY KEY,
    PROGRAM_ID INT REFERENCES SCHOOL.ACADEMIC_PROGRAM(PROGRAM_ID),
    COURSE_ID INT REFERENCES SCHOOL.COURSE(COURSE_ID),
    REQUIREMENT_TYPE VARCHAR(50),
    VERSION VARCHAR(20)
);

-- ASSIGNMENT
CREATE TABLE IF NOT EXISTS SCHOOL.ASSIGNMENT (
    ASSIGNMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN,
    MAX_POINTS INT
);

-- COURSE_INSTANCE
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE_INSTANCE (
    INSTANCE_ID SERIAL PRIMARY KEY,
    COURSE_ID INT REFERENCES SCHOOL.COURSE(COURSE_ID),
    FACULTY_ID INT REFERENCES SCHOOL.FACULTY(FACULTY_ID),
    TERM VARCHAR(20),
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    LOCATION VARCHAR(100)
);

-- COURSE_ASSIGNMENT (Assignment Submission)
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE_ASSIGNMENT (
    COURSE_ASSIGNMENT_ID SERIAL PRIMARY KEY,
    INSTANCE_ID INT REFERENCES SCHOOL.COURSE_INSTANCE(INSTANCE_ID),
    ASSIGNMENT_ID INT REFERENCES SCHOOL.ASSIGNMENT(ASSIGNMENT_ID),
    STUDENT_ID INT REFERENCES SCHOOL.STUDENT(STUDENT_ID),
    POINTS_EARNED INT NOT NULL,
    LETTER_GRADE VARCHAR(5) NOT NULL
);