CREATE SCHEMA IF NOT EXISTS SCHOOL;

-- JOB
CREATE TABLE IF NOT EXISTS SCHOOL.JOB (
    JOB_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    IS_MANAGEMENT BOOLEAN NOT NULL
);

-- DEPARTMENT
CREATE TABLE IF NOT EXISTS SCHOOL.DEPARTMENT (
    DEPARTMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- FACULTY
CREATE TABLE IF NOT EXISTS SCHOOL.FACULTY (
    FACULTY_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    TERM_DATE DATE NULL,
    DEPARTMENT_ID INT REFERENCES SCHOOL.DEPARTMENT(DEPARTMENT_ID) NOT NULL,
    JOB_ID INT REFERENCES SCHOOL.JOB(JOB_ID) NOT NULL
);

-- ACADEMIC_PROGRAM
CREATE TABLE IF NOT EXISTS SCHOOL.ACADEMIC_PROGRAM (
    PROGRAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT INT REFERENCES SCHOOL.DEPARTMENT(DEPARTMENT_ID) NOT NULL,
    DEGREE_TYPE VARCHAR(20) NOT NULL
);

-- STUDENT
CREATE TABLE IF NOT EXISTS SCHOOL.STUDENT (
    STUDENT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    EXPECTED_GRADUATION_DATE DATE NOT NULL,
    PROGRAM_ID INT REFERENCES SCHOOL.ACADEMIC_PROGRAM(PROGRAM_ID) NOT NULL
);

-- COURSE
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE (
    COURSE_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    IS_ACTIVE BOOLEAN
);

-- PROGRAM_COURSE_REQUIREMENT
CREATE TABLE IF NOT EXISTS SCHOOL.PROGRAM_COURSE_REQUIREMENT (
    REQUIREMENT_ID SERIAL PRIMARY KEY,
    PROGRAM_ID INT REFERENCES SCHOOL.ACADEMIC_PROGRAM(PROGRAM_ID) NOT NULL,
    COURSE_ID INT REFERENCES SCHOOL.COURSE(COURSE_ID) NOT NULL,
    REQUIREMENT_TYPE VARCHAR(50) NOT NULL,
    VERSION VARCHAR(20) NOT NULL
);

-- ASSIGNMENT
CREATE TABLE IF NOT EXISTS SCHOOL.ASSIGNMENT (
    ASSIGNMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    MAX_POINTS INT NOT NULL
);

-- COURSE_INSTANCE
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE_INSTANCE (
    INSTANCE_ID SERIAL PRIMARY KEY,
    COURSE_ID INT REFERENCES SCHOOL.COURSE(COURSE_ID) NOT NULL,
    FACULTY_ID INT REFERENCES SCHOOL.FACULTY(FACULTY_ID) NOT NULL,
    TERM VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    LOCATION VARCHAR(100) NOT NULL
);

-- COURSE_ASSIGNMENT (Assignment Submission)
CREATE TABLE IF NOT EXISTS SCHOOL.COURSE_ASSIGNMENT (
    COURSE_ASSIGNMENT_ID SERIAL PRIMARY KEY,
    INSTANCE_ID INT REFERENCES SCHOOL.COURSE_INSTANCE(INSTANCE_ID) NOT NULL,
    ASSIGNMENT_ID INT REFERENCES SCHOOL.ASSIGNMENT(ASSIGNMENT_ID) NOT NULL,
    STUDENT_ID INT REFERENCES SCHOOL.STUDENT(STUDENT_ID) NOT NULL,
    POINTS_EARNED INT NULL,
    LETTER_GRADE VARCHAR(5) NULL
);

-- USERS
CREATE TABLE IF NOT EXISTS SCHOOL.USERS (
  ID SERIAL PRIMARY KEY,
  USERNAME TEXT UNIQUE NOT NULL,
  PASSWORD_HASH TEXT NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ROLES
CREATE TABLE IF NOT EXISTS SCHOOL.ROLES (
  ID SERIAL PRIMARY KEY,
  NAME TEXT UNIQUE NOT NULL
);

-- USER_ROLES
CREATE TABLE IF NOT EXISTS SCHOOL.USER_ROLES (
  USER_ID INT REFERENCES SCHOOL.USERS(ID),
  ROLE_ID INT REFERENCES SCHOOL.ROLES(ID),
  PRIMARY KEY (USER_ID, ROLE_ID)
);
