-- STUDENT
CREATE TABLE STUDENT (
    STUDENT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE,
    EXPECTED_GRADUATION_DATE DATE,
    PROGRAM_ID INT REFERENCES ACADEMIC_PROGRAM(PROGRAM_ID)
);

-- FACULTY
CREATE TABLE FACULTY (
    FACULTY_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    HIRE_DATE DATE,
    TERM_DATE DATE,
    DEPARTMENT_ID INT REFERENCES DEPARTMENT(DEPARTMENT_ID),
    JOB_ID INT REFERENCES JOB(JOB_ID)
);

-- DEPARTMENT
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    DEPARTMENT_CHAIR INT REFERENCES FACULTY(FACULTY_ID)
);

-- JOB
CREATE TABLE JOB (
    JOB_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE BOOLEAN,
    IS_MANAGEMENT BOOLEAN
);

-- ACADEMIC_PROGRAM
CREATE TABLE ACADEMIC_PROGRAM (
    PROGRAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    DEPARTMENT INT REFERENCES DEPARTMENT(DEPARTMENT_ID),
    DEGREE_TYPE VARCHAR(20)
);

-- COURSE
CREATE TABLE COURSE (
    COURSE_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE BOOLEAN
);

-- PROGRAM_COURSE_REQUIREMENT
CREATE TABLE PROGRAM_COURSE_REQUIREMENT (
    REQUIREMENT_ID SERIAL PRIMARY KEY,
    PROGRAM_ID INT REFERENCES ACADEMIC_PROGRAM(PROGRAM_ID),
    COURSE_ID INT REFERENCES COURSE(COURSE_ID),
    REQUIREMENT_TYPE VARCHAR(50),
    VERSION VARCHAR(20)
);

-- ASSIGNMENT
CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE BOOLEAN,
    MAX_POINTS INT
);

-- COURSE_INSTANCE
CREATE TABLE COURSE_INSTANCE (
    INSTANCE_ID SERIAL PRIMARY KEY,
    COURSE_ID INT REFERENCES COURSE(COURSE_ID),
    FACULTY_ID INT REFERENCES FACULTY(FACULTY_ID),
    TERM VARCHAR(20),
    START_DATE DATE,
    END_DATE DATE,
    LOCATION VARCHAR(100)
);

-- COURSE_ASSIGNMENT (Assignment Submission)
CREATE TABLE COURSE_ASSIGNMENT (
    COURSE_ASSIGNMENT_ID SERIAL PRIMARY KEY,
    INSTANCE_ID INT REFERENCES COURSE_INSTANCE(INSTANCE_ID),
    ASSIGNMENT_ID INT REFERENCES ASSIGNMENT(ASSIGNMENT_ID),
    STUDENT_ID INT REFERENCES STUDENT(STUDENT_ID),
    POINTS_EARNED INT,
    LETTER_GRADE VARCHAR(5)
);